#! /bin/sh

TINT2_BIN=/usr/bin/tint2
TINT2_ARGS=
export DISPLAY=:0.0
export G_SLICE=always-malloc

start() {
	printf "Starting tint2: "
	start-stop-daemon -S -q -b --exec $TINT2_BIN -- $TINT2_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping tint2: "
	kill -9 `pidof tint2`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
        start
        ;;
	stop)
	    stop
		;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
