#! /bin/sh

INTERFACE=wlan0
WLAN_MODULE_NAME=8821au
GATEWAY_IP=192.168.6.1

wait_iface() {
if [ "$1" -a ! -e "/sys/class/net/$2" ]; then
    time_left=$1
    printf "Waiting for interface %s to appear" "$2"
    while [ $time_left -gt 0 ]; do
        if [ -e "/sys/class/net/$2" ]; then
            printf "\n"
            return 0
        fi
        sleep 1
        printf "."
        : $((time_left -= 1))
    done
    printf " timeout!\n"
    return 1
fi
return 0
}

start()
{
    lsmod | grep $WLAN_MODULE_NAME
    if [ $? != 0 ]; then
        modprobe $WLAN_MODULE_NAME
    fi
    wait_iface 3 $INTERFACE
    if [ $? = 0 ]; then
    ifconfig $INTERFACE $GATEWAY_IP
        hostapd -s -B /etc/hostapd.conf
    fi
}

stop()
{
	kill -15 `pidof hostapd`
    rmmod $WLAN_MODULE_NAME
}

restart()
{
	stop
    sleep 2
    start
}

case "$1" in
	start)
          start
		;;
	stop)
          stop
		;;
    restart)
        	restart
        ;;
	*)
		exit 1
		;;
esac
