#! /bin/sh

BOA_BIN=/usr/sbin/boa
BOA_SERVER_ROOT=/etc/boa-AriaNg

case "$1" in
	start)
		printf "Starting Boa web server... "
		$BOA_BIN -c $BOA_SERVER_ROOT
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "stopping Boa web server... "
		kill -9 `pidof boa`
		[ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
	*)
		exit 1
		;;
esac
