#! /bin/sh

CROND=/usr/sbin/crond
CRONTAB=/usr/bin/crontab
MEM_DIR=/tmp

case "$1" in
	start)
		ln -sf /etc/cron_change_governor $MEM_DIR/cron_change_governor
		$CRONTAB -c $MEM_DIR $MEM_DIR/cron_change_governor
        [ $? = 0 ] && $CROND -c $MEM_DIR
		;;
	stop)
		kill -9 $(pidof crond)
        ;;
    restart)
        ;;
	*)
		exit 1
		;;
esac
