#! /bin/sh

NAT_IP=192.168.6.0

case "$1" in
	start)
        echo 1 > /proc/sys/net/ipv4/ip_forward
        modprobe nf_log_ipv4
        iptables -F
        iptables -t nat -F
        if [ -e "/sys/class/net/wlan0" ]; then
            iptables -A INPUT -i wlan1 -d 192.168.6.1 -j ACCEPT
            iptables -A INPUT -s 192.168.8.1 -j ACCEPT
            iptables -A INPUT -s 192.168.8.0/24 -j DROP
            iptables -t nat -A POSTROUTING -s ${NAT_IP}/24 -o wlan0 -j MASQUERADE
        fi
		;;
	stop)
		;;
	*)
		exit 1
		;;
esac
