#! /bin/sh

NAT_IP=192.168.6.0

case "$1" in
	start)
        echo 1 > /proc/sys/net/ipv4/ip_forward
        iptables -F
        [ -e "/sys/class/net/wlan0" ] && iptables -t nat -A POSTROUTING -s ${NAT_IP}/24 -o wlan0 -j MASQUERADE
		;;
	stop)
		;;
	*)
		exit 1
		;;
esac
