#! /bin/sh

INTERFACE=wlan0

case "$1" in
	start)
		modprobe rtl8192cu
		wpa_supplicant -B -Dnl80211 -i$INTERFACE -c/etc/wpa_supplicant.conf
		udhcpc -b -i $INTERFACE
		;;
	stop)
		;;
	*)
		exit 1
		;;
esac
